# Generated by Django 4.2.2 on 2023-06-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='airplane_id',
            new_name='airplane',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='passport_id',
            new_name='passport',
        ),
    ]
