# Generated by Django 4.2.2 on 2023-06-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_airplane_id_orders_airplane_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='routes',
            name='city_arrival',
            field=models.CharField(default='Warsaw', max_length=40),
        ),
        migrations.AddField(
            model_name='routes',
            name='city_departure',
            field=models.CharField(default='Minsk', max_length=40),
        ),
        migrations.AddField(
            model_name='routes',
            name='price',
            field=models.PositiveIntegerField(default=328),
        ),
        migrations.AlterField(
            model_name='passports',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='passports',
            name='date_of_expire',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='passports',
            name='date_of_issue',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
