# Generated by Django 4.2.2 on 2023-06-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_passports_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='passport',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
