# Generated by Django 4.2.2 on 2023-07-09 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_routes_date_arrival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(default=0)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.airplanes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.users')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='seat_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.seats'),
        ),
    ]
