# Generated by Django 4.2.2 on 2023-07-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_orders_seat_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together={('user', 'airplane', 'seat_number')},
        ),
    ]
