# Generated by Django 4.2.2 on 2023-07-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0014_remove_orders_airplane_remove_orders_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplanes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.airplanes')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Passports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('date_of_issue', models.DateField()),
                ('date_of_expire', models.DateField()),
                ('photo', models.ImageField(null=True, upload_to='photo_user')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_departure', models.CharField(default='Belarus', max_length=40)),
                ('country_arrival', models.CharField(default='Poland', max_length=40)),
                ('city_departure', models.CharField(default='Minsk', max_length=40)),
                ('city_arrival', models.CharField(default='Warsaw', max_length=40)),
                ('date_departure', models.DateTimeField()),
                ('date_arrival', models.DateTimeField()),
                ('price', models.PositiveIntegerField(default=328)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('orders_users_mtm', models.ManyToManyField(through='booking.OrdersUsers', to='booking.orders')),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.passports')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(null=True)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.airplanes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.users')),
            ],
            options={
                'unique_together': {('airplane', 'seat_number')},
            },
        ),
        migrations.AddField(
            model_name='ordersusers',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.seats'),
        ),
        migrations.AddField(
            model_name='ordersusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='route',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.routes'),
        ),
    ]
