# Generated by Django 4.2.2 on 2023-07-29 11:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('booking', '0016_remove_orders_airplane_remove_orders_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iata_aircraft', models.CharField(default='733', max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iata_airline', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Passports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('sex', models.CharField(choices=[('male', 'M'), ('female', 'F')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('date_of_issue', models.DateField()),
                ('date_of_expire', models.DateField()),
                ('photo', models.ImageField(null=True, upload_to='photo_user')),
            ],
        ),
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_departure', models.CharField(max_length=20)),
                ('iata_arrival', models.CharField(max_length=20)),
                ('date_departure', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='booking_users', to='auth.group', verbose_name='groups')),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport_users', to='booking.passports')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='booking_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_departure', models.CharField(default='Belarus', max_length=40)),
                ('country_arrival', models.CharField(default='Poland', max_length=40)),
                ('city_departure', models.CharField(default='Minsk', max_length=40)),
                ('city_arrival', models.CharField(default='Warsaw', max_length=40)),
                ('date_arrival', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_route', to='booking.aircrafts')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airline_route', to='booking.airlines')),
                ('temporary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_route', to='booking.temporary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_route', to='booking.users')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('paid', 'P'), ('unpaid', 'U'), ('rejected', 'R')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='booking.users')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_seat', to='booking.aircrafts')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_seat', to='booking.orders')),
            ],
            options={
                'unique_together': {('aircraft', 'seat_number')},
            },
        ),
    ]
