# Generated by Django 4.2.2 on 2023-07-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0016_remove_orders_airplane_remove_orders_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('date_of_issue', models.DateField()),
                ('date_of_expire', models.DateField()),
                ('photo', models.ImageField(null=True, upload_to='photo_user')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.passports')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_departure', models.CharField(default='Belarus', max_length=40)),
                ('country_arrival', models.CharField(default='Poland', max_length=40)),
                ('city_departure', models.CharField(default='Minsk', max_length=40)),
                ('city_arrival', models.CharField(default='Warsaw', max_length=40)),
                ('date_departure', models.DateTimeField()),
                ('date_arrival', models.DateTimeField()),
                ('price', models.PositiveIntegerField(default=328)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.aircrafts')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('p', 'paid'), ('n', 'not paid'), ('r', 'rejected')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.users')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.aircrafts')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.orders')),
            ],
            options={
                'unique_together': {('aircraft', 'seat_number')},
            },
        ),
    ]
