# Generated by Django 4.2.2 on 2023-07-19 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('paid', 'P'), ('unpaid', 'U'), ('rejected', 'R')], max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='booking.users'),
        ),
        migrations.AlterField(
            model_name='passports',
            name='sex',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F')], max_length=10),
        ),
        migrations.AlterField(
            model_name='routes',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_routes', to='booking.aircrafts'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='seats',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_seats', to='booking.aircrafts'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_seats', to='booking.orders'),
        ),
        migrations.AlterField(
            model_name='users',
            name='passport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport_users', to='booking.passports'),
        ),
    ]
