# Generated by Django 4.2.2 on 2023-07-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_orders_status_alter_orders_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('iata_airline', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='aircrafts',
            name='iata_aircraft',
            field=models.CharField(default='733', max_length=20),
        ),
        migrations.AddField(
            model_name='routes',
            name='iata_arrival',
            field=models.CharField(default='WMI', max_length=3),
        ),
        migrations.AddField(
            model_name='routes',
            name='iata_departure',
            field=models.CharField(default='MSQ', max_length=3),
        ),
    ]
