# Generated by Django 4.2.2 on 2023-07-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_airlines_aircrafts_iata_aircraft_routes_iata_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='airline_routes', to='booking.airlines'),
            preserve_default=False,
        ),
    ]
