# Generated by Django 4.2.2 on 2023-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_routes_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_departure', models.CharField(max_length=3)),
                ('iata_arrival', models.CharField(max_length=3)),
                ('date_departure', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='routes',
            name='date_departure',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='iata_arrival',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='iata_departure',
        ),
        migrations.AlterField(
            model_name='routes',
            name='date_arrival',
            field=models.DateField(),
        ),
    ]
