# Generated by Django 4.2.2 on 2023-07-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_temporarydata_remove_routes_date_departure_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemporaryData',
            new_name='Temporary',
        ),
    ]
