# Generated by Django 4.2.2 on 2023-07-22 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_rename_temporarydata_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='temporary',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temporary_routes', to='booking.temporary'),
            preserve_default=False,
        ),
    ]
