# Generated by Django 4.2.2 on 2023-07-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_routes_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary',
            name='iata_arrival',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='temporary',
            name='iata_departure',
            field=models.CharField(max_length=20),
        ),
    ]
